version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    branches:
      only:
        - master
        - develop
        - feature/deployment
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-nrweb-{{ checksum "package.json" }}
            - v1-nrweb-
      - run:
          name: Dependency Setup
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-nrweb-{{ checksum "package.json" }}
      - run:
          name: Test Runner
          command: yarn test:nowatch --runInBand --ci
      - store_test_results:
          path: ./test_results
  deploy:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: Install Firebase CLI
          command: yarn add --dev firebase-tools
      - run:
          name: Yarn Build
          command: yarn build
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - feature/deployment